### PR TITLE
LPS-76501 Fall back to LocaleUtil

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @natocesarrego 

This is an additional commit for LPS-76501 to fix the breaking tests.
https://github.com/liferay/liferay-portal/pull/2509#issuecomment-356431011

Best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by natocesarrego** [comment]
Hi @IstvanD,

Once your solution is fine and this commit is just to fix a regression revealed by CI, can you please send it straight to the PT?

Thanks in advance.

**Comment by IstvanD** [comment]
Hi @natocesarrego 

Sure.
Is it the liferay user whom I should sent it to?
Thanks!

Best regards,
István

**Comment by natocesarrego** [comment]
Yes, my friend!

**Comment by IstvanD** [comment]
Sure thing
https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/667

**Pull request closed without merging**
