### PR TITLE
LPS-74438 CKEditor cannot be resized in a repeatable field

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @natocesarrego 

As per your request in https://github.com/natocesarrego/liferay-portal/pull/92#issuecomment-326963269, I'm sending the pull to the com-liferay-dynamic-data-mapping subrepo.

Best regards,
István

### CODE REVIEW

**Comment by natocesarrego** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natocesarrego** [comment]
Hey @IstvanD,

Sorry for take so long to review it, but, as you probably know, I received too much requests recently and this caused the delay. 😞 

Additionally, feel free to send your pulls straight to the PT. If you're unsure and need a second opinion about a pull, then you can first send it to me. 😉 

Once this pull was already merged in https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/379, I'm closing this pull.

Best.

**Comment by IstvanD** [comment]
Hey @natocesarrego 

No problem, and thanks for notifying me about liferay#379 being merged. :)

Best regards,
István

UPDATE: now I see that the fix is also merged to liferay-portal.

**Comment by natocesarrego** [comment]
No problem, @IstvanD. Actually, it's a pleasure to help.

Best.

**Pull request closed without merging**
